lib: A tutorial and some 'modify' monad rules for Lib.EquivValid
seL4/l4v pull request #131
Opened 2020-10-30 12:14 UTC by robs-cse

Thanks to Toby Murray (@tobycmurray) for early feedback.

Signed-off-by: Robert Sison <robert.sison@unimelb.edu.au>

2020-10-30 12:21 UTC, robs-cse commented
The tutorial can be built to PDF by running `./isabelle/bin/isabelle build -d . EVTutorial` from the l4v directory.

2020-11-01 23:08 UTC, lsf37 commented
Ok to ignore the link checker failures, these are hopefully temporary, and in any case unrelated. Also fine to ignore the `Refine` failures. They're running out of store and I should probably remove them from the test, because that happens too frequently now.

2020-11-02 00:22 UTC, lsf37 requested changes
The tutorial itself looks very nice from my side!

One small change request before I can approve: can you please add it to the regression test infrastructure, i.e. to the appropriate `tests.xml` and make sure it is also called in the corresponding github workflow. I think adding it to `.github/workflows/proof.yml `  in the run that calls `ASpec` and `AInvs` would make sense (this one also builds `Lib` as a dependency, IIRC).

2020-11-02 03:07 UTC, lsf37 commented on lib/EVTutorial/ROOT
> +  options [document = pdf, document_output = "output"]
Unless you really want the user to inspect the generated sources, I would usually not add an `output` option.

```suggestion
  options [document = pdf]
```

2020-11-02 03:52 UTC, robs-cse commented
The force-push to commit 1ee13dd is just a rebase, with some minor fixes to the last commit message.

2020-11-02 04:12 UTC, mbrcknl approved these changes
I've not read every detail of the tutorial, but the bits I looked at were great! I look forward to working through the rest...

Thanks for doing this!

2020-11-02 04:31 UTC, lsf37 approved these changes
👍

2020-11-02 22:57 UTC, robs-cse commented
(Force-push to commit 3bd44af is another rebase.)

2020-11-15 22:56 UTC, robs-cse commented
@lsf37 has advised that the two reviews are sufficient to approve the merge. The force push to commit e2194d4 is a rebase to the current mainline head, squashing all the fixup commits.

2020-11-15 23:18 UTC, lsf37 commented
Ok to ignore the failed link test. Apparently the nicta.com.au certificates have expired.

2020-11-16 19:05 UTC, robs-cse commented
The force push to commit 19312b5 rebased to the mainline head, and passed [this testboard run](https://bamboo.ts.data61.csiro.au/browse/L4V-TESTBOARD-658). I'll "Rebase and Merge" it now - thank you again @lsf37 and @mbrcknl.

2020-11-16 19:06 UTC, merged